
server.port=8177


spring.datasource.url=jdbc:postgresql://localhost:5432/agrosmart_db
spring.datasource.username=agrosmart_user
spring.datasource.password=AgroSmart2026!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.timeout=30s


logging.level.ec.edu.espe.agrosmart=INFO
logging.level.org.springframework.web=WARN